### ISSUE TITLE
GeoJSON implementation - geojson-kdbush?

### ISSUE THREAD

**Issue by DenisCarriere** [mourner/kdbush#12]
This library is awesome 🥇!

@mourner any interest of having a `GeoJSON` implementation, similar to [`geojson-rbush`](https://github.com/DenisCarriere/geojson-rbush)?

Let me know and I can aim to have it as minimalistic like your repos.

👍/ 👎  the idea and close this issue whenever you like.

**Comment by mourner** [comment]
Yes, feel free to make a repo! Also check out https://github.com/mourner/geokdbush if you haven't — will probably be necessary too.

**Comment by DenisCarriere** [comment]
👍 Thanks for the tip, I'll look into both of these when I have some spare time. Also might send over a PR for a Typescript definition (my way of learning how the library works).

Cheers,
