### ISSUE TITLE
[Feature Request] Import from /Export to Array Buffer, like Flatbush

### ISSUE THREAD

**Issue by hydrosquall** [mourner/kdbush#31]
Hi,

Thanks for the work on this very helpful library!

I landed here from a comment in the companion library, which has methods that support serializing the index to disk (via the `data` property on an index instance), and loading that serialized result back conveniently (via `Flatbush.from`). It would be really convenient to have those same methods available for this library too.

 https://github.com/mourner/flatbush/issues/19#issuecomment-429104887

**Comment by mourner** [comment]
Yes, I'd like to bring it on par with Flatbush in this regard — will hopefully take on this in the next few weeks!
