### ISSUE TITLE
range function returns with an empty array.

### ISSUE THREAD

**Issue by hussyd** [mourner/kdbush#43]
Red points are the min/max points of the boundary box.
Blue points are my coordinates in the tree.
As you can see there are a few points that are inside the boundary box, but KDBush returns with an empty array.
Why could this happen?

![image](https://github.com/mourner/kdbush/assets/13572157/7520741a-b04b-4ef2-9c1b-7ad977f75969)

**Comment by mourner** [comment]
I can't say for sure (I'd need a reproducible minimal live test case for this), but maybe because the corners of the bounding box have Y axis flipped? E.g. since bbox should be minimum-maximum on both axes, the min/max points should have been (-34, -2) and (90, 103) (so, opposite diagonals).

**Comment by hussyd** [comment]
Hi @mourner,
at first, thanks for your quick reply!
Yes, that was the problem, now it works! 🙏
