### ISSUE TITLE
not working in nodejs environment

### ISSUE THREAD

**Issue by chr4ss12** [mourner/kdbush#46]
hi, this library does not work in nodejs environment:

Error [ERR_REQUIRE_ESM]: require() of ES Module [project_root]/node_modules/kdbush/index.js from [project_root]/index.js not supported.
Instead, change the require of [project_root]/node_modules/kdbush/index.js in [project_root]/index.js to a dynamic import() which is available in all CommonJS modules.

I have tried every combination I can think of,

require()
import()

dynamic import (await import()),

but they all give the same error.

**Comment by mourner** [comment]
`kdbush` doesn't support CommonJS since v4 by design. If you're project complains about `require` even when you use `import`, it's an issue with your setup — not something I can fix on `kdbush` side.
