### ISSUE TITLE
Behaviour when X wraps at 1/0

### ISSUE THREAD

**Issue by jlaine** [mourner/kdbush#7]
Hi,

First of all thanks for kdbush, it is indeed very fast! I have been browsing the code, and one question comes to mind: is there any provision for X (aka longitude) wraps at the 1/0 boundary?

Thanks,
Jeremy

**Comment by mourner** [comment]
No, KDBush is a purely geometric library — it uses ordinary 2D coordinates. Any longitude wrapping logic must be implemented elsewhere.

**Comment by jlaine** [comment]
Ok, makes sense, I guess the next step is to examine the supercluster code then!
